name: Code quality.

on: [push, pull_request]

jobs:
  code-imports-typing-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    timeout-minutes: 8
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy isort

      - name: Code style.
        run: |
          echo 'Files to be linted: '
          echo $(git ls-files '*.py')
          pylint -v $(git ls-files '*.py')

      - name: Type checking.
        run: 
          mypy generate_playlist.py

      - name: Import ordering.
        run:
          isort --check .
